# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_UI_.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import pyqtgraph as pg
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(870, 778)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 871, 751))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        
        self.graph = pg.RawImageWidget(self.tab2, scaled=True)
        self.graph.setGeometry(QtCore.QRect(240, 80, 600, 600))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.graph.setFont(font)
        self.graph.setObjectName("graph")
        
        self.label_7 = QtWidgets.QLabel(self.tab2)
        self.label_7.setGeometry(QtCore.QRect(350, 10, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        font.setPointSize(21)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_7.setStyleSheet("border : 3px solid blue")
        self.label_7.setFont(QtGui.QFont('Consolas', 25))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        
        self.btn_UR = QtWidgets.QPushButton(self.tab2)
        self.btn_UR.setGeometry(QtCore.QRect(20, 160, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_UR.setFont(font)
        self.btn_UR.setObjectName("btn_UR")
        
        self.ctrl_check = QtWidgets.QCheckBox(self.tab2)
        self.ctrl_check.setGeometry(QtCore.QRect(70, 340, 100, 51))
        self.ctrl_check.setObjectName("ctrl_check")
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.ctrl_check.setFont(font)
        
        self.pred_check = QtWidgets.QCheckBox(self.tab2)
        self.pred_check.setGeometry(QtCore.QRect(70, 240, 100, 51))
        self.pred_check.setObjectName("pred_check")
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.pred_check.setFont(font)
        
        self.btn_start = QtWidgets.QPushButton(self.tab2)
        self.btn_start.setGeometry(QtCore.QRect(20, 80, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_start.setFont(font)
        self.btn_start.setObjectName("btn_start")
        
        self.tabWidget.addTab(self.tab2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "GESTURE "))
        self.btn_UR.setText(_translate("MainWindow", "UR"))
        self.btn_start.setText(_translate("MainWindow", "START"))
        self.pred_check.setText(_translate("MainWindow", "Predict?"))
        self.ctrl_check.setText(_translate("MainWindow", "Control?"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "Realtime"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())